### ISSUE TITLE
Breaks on ' in query

### ISSUE THREAD

**Issue by codelamb** [chrisbra/wikipedia2text#3]
It seems a program breaks on input containing ' , e.g. $wikipedia2text O'Henry

**Comment by chrisbra** [comment]
Hm? Cannot reproduce. This will redirect to http://en.wikipedia.org/wiki/O%27Henry Which I would say is correct. Where do you think it should redirect to?

**Comment by codelamb** [comment]
I used it from Bash on Windows 10, maybe there's the rub, it has limited functionality. Sorry I didn't
mention that.

[image: Įterptasis vaizdas 1]

2017-01-28 22:48 GMT+02:00 Christian Brabandt <notifications@github.com>:

**Comment by xtaran** [comment]
@codelamb: What's the exact error message? In every bourne-shell compatible shell (like e.g. bash) you need to quote single quotes in commands. Try using one of these:

```
wikipedia2text O\'Henry
wikipedia2text "O'Henry"
```

**Comment by codelamb** [comment]
These two works fine. Thank you for suggestion. 
Bash does not return any error code, just empty line beginning with symbol ">" and prompt. I can escape it only with ctrl + c
