### ISSUE TITLE
Summary is broken

### ISSUE THREAD

**Issue by elig0n** [chrisbra/wikipedia2text#5]
title

**Comment by chrisbra** [comment]
which summary?

**Comment by elig0n** [comment]
the summary (short) option : -s
returns incomplete or out of bounds output

**Comment by chrisbra** [comment]
I suppose you mean the help/usage output? I shortened it a bit to fit into a 80 character wide terminal. 
(note -s usually shows only the output from the wikiepedia. The script does not reformat the output from the browser, so you might be able to tweak that from your browser options).

**Comment by elig0n** [comment]
I mean the "-s  display only a summary" option which I understand to show only the summary top part of a wikipedia article. Using supposedly 'lynx -dump' with `|grep -v copyright | head -n 22   | tail -n 17`.

**Comment by chrisbra** [comment]
Now you know, why should be precise when creating an issue. So is it using lynx? Can you check with a different browser? For me, it is using w3m, which looks okay

**Comment by chrisbra** [comment]
is this still a problem?

**Comment by elig0n** [comment]
Yes. Summary is not appearing correctly, see this:
https://imgur.com/a/fRWTnLK

**Comment by chrisbra** [comment]
looks like the decision to drop lines after the first initial 17 lines is a bit arbitrary. How about we make this configurable?

**Comment by elig0n** [comment]
sure, lacking a better option...

**Comment by elig0n** [comment]
I've sent an alternative solution as a PR

**Comment by chrisbra** [comment]
thanks, I have included that. So closing.
