### ISSUE TITLE
No Browser found

### ISSUE THREAD

**Issue by greenzebraelephant** [chrisbra/wikipedia2text#8]
I get No Browser found when trying to run this with a Wikipedia link. But I have Opera and Firefox on my Ubuntu.

**Comment by chrisbra** [comment]
What are you trying to achieve? This project here is for allowing users to read wikipediatext on the console and provides a text only interface to the wikipedia. I believe you need something like w3m/lynx/links etc.

**Comment by greenzebraelephant** [comment]
Readme doesn't say I need w3m/lynx/links etc. In fact it says "Alternatively it opens the Wikipedia article in a (possibly GUI) web browser"

**Comment by chrisbra** [comment]
Yes and I think it does, if you give it proper arguments. The text-browsers are however needed to convert the html into readable text. So have you tried using either -o or -b argument?
